# Use the official Java SE 17 image as the base image
FROM openjdk:17-jdk

# using bash shell
SHELL ["/bin/bash", "-c"]

# Set the working directory to /app
ONBUILD WORKDIR /app

# Copy the app and its dependencies
ONBUILD COPY /app .

# Run mvn package to compile the Java code
ONBUILD RUN mvn package

# Remove the sources and other unnecessary files
ONBUILD RUN rm -rf src pom.xml

# Run the app with the resulting jar file
ONBUILD CMD ["java", "-jar", "target/app.jar"]
