# Use the official Python image as the base image
FROM python:3.10

# using bash shell
SHELL ["/bin/bash", "-c"]

# Set the working directory to /app
WORKDIR /app

# Copy the dependencies file(s) to the image
COPY requirements.txt ./

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application sources
COPY . .

# Run the command to execute the application
CMD ["python", "-m", "app"]